template: |
  ## What’s Changed

  $CHANGES

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'IMPORTANT'
    label: 'type: important'
  - title: 'New'
    label: 'type: feature'
  - title: 'Bug Fixes'
    labels:
      - 'type: bug'
      - 'type: maintenance'
  - title: 'Documentation'
    label: 'type: docs'
  - title: 'Dependency Updates'
    label: 'type: dependencies'

version-resolver:
  major:
    labels:
      - 'type: backwards incompatible'
  minor:
    labels:
      - 'type: important'
      - 'type: feature'
  patch:
    labels:
      - 'type: bug'
      - 'type: maintenance'
      - 'type: docs'
      - 'type: dependencies'

exclude-labels:
  - 'skip-changelog'
