# build the server using java 8 jdk
build:
  - image: java:8-jdk
    env_file:
      - mold.sonar.env
    workdir: /conductor
    commands:
      - ./gradlew build -x test
      - if [ "${SONAR_ENABLED}" -eq "1" ]; then ./gradlew sonarqube -x test -Dsonar.projectKey=conductor -Dsonar.branch.name="${SONAR_BRANCH}" -Dsonar.host.url="${SONAR_HOST}" -Dsonar.login="${SONAR_LOGIN}"; else echo "SONAR_ENABLED ${SONAR_ENABLED}. Analysis skipped."; fi

# build the runtime artifact images..
artifacts:
  publish:
    - master
    - v${APP_VERSION}
  registry: 583623634344.dkr.ecr.us-west-2.amazonaws.com
  images:
    - name: conductor
      dockerfile: docker/server/Dockerfile
      tags:
        - "${APP_VERSION}-server"
        - server
    - name: conductor
      dockerfile: docker/ui/Dockerfile
      tags:
        - "${APP_VERSION}-ui"
        - ui
    - name: conductor
      dockerfile: docker/archiver/Dockerfile
      tags:
        - "${APP_VERSION}-archiver"
        - archiver
