# build the server using java 8 jdk
build:
  - image: java:8-jdk
    workdir: /conductor
    commands:
     - ./gradlew build -x test 

# build the runtime artifact images..
artifacts:
  publish:
  - master
  - v${APP_VERSION}
  registry: 583623634344.dkr.ecr.us-west-2.amazonaws.com
  images:
  - name: conductor
    dockerfile: docker/server/Dockerfile
    tags:
        - "${APP_VERSION}-server"
        - server
  - name: conductor
    dockerfile: docker/ui/Dockerfile
    tags:
        - "${APP_VERSION}-ui"
        - ui
        
