apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: netflixconductor
    context: .
    docker:
      network: host
      dockerfile: docker/server/Dockerfile
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/netflixconductor:server-{{.VERSION}}'
