// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/workflow_service.proto

package workflows // import "github.com/netflix/conductor/client/gogrpc/conductor/grpc/workflows"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import search "github.com/netflix/conductor/client/gogrpc/conductor/grpc/search"
import model "github.com/netflix/conductor/client/gogrpc/conductor/model"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StartWorkflowResponse struct {
	WorkflowId           string   `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartWorkflowResponse) Reset()         { *m = StartWorkflowResponse{} }
func (m *StartWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*StartWorkflowResponse) ProtoMessage()    {}
func (*StartWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{0}
}
func (m *StartWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartWorkflowResponse.Unmarshal(m, b)
}
func (m *StartWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartWorkflowResponse.Marshal(b, m, deterministic)
}
func (dst *StartWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartWorkflowResponse.Merge(dst, src)
}
func (m *StartWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_StartWorkflowResponse.Size(m)
}
func (m *StartWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartWorkflowResponse proto.InternalMessageInfo

func (m *StartWorkflowResponse) GetWorkflowId() string {
	if m != nil {
		return m.WorkflowId
	}
	return ""
}

type GetWorkflowsRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CorrelationId        []string `protobuf:"bytes,2,rep,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	IncludeClosed        bool     `protobuf:"varint,3,opt,name=include_closed,json=includeClosed,proto3" json:"include_closed,omitempty"`
	IncludeTasks         bool     `protobuf:"varint,4,opt,name=include_tasks,json=includeTasks,proto3" json:"include_tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWorkflowsRequest) Reset()         { *m = GetWorkflowsRequest{} }
func (m *GetWorkflowsRequest) String() string { return proto.CompactTextString(m) }
func (*GetWorkflowsRequest) ProtoMessage()    {}
func (*GetWorkflowsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{1}
}
func (m *GetWorkflowsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkflowsRequest.Unmarshal(m, b)
}
func (m *GetWorkflowsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkflowsRequest.Marshal(b, m, deterministic)
}
func (dst *GetWorkflowsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkflowsRequest.Merge(dst, src)
}
func (m *GetWorkflowsRequest) XXX_Size() int {
	return xxx_messageInfo_GetWorkflowsRequest.Size(m)
}
func (m *GetWorkflowsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkflowsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkflowsRequest proto.InternalMessageInfo

func (m *GetWorkflowsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetWorkflowsRequest) GetCorrelationId() []string {
	if m != nil {
		return m.CorrelationId
	}
	return nil
}

func (m *GetWorkflowsRequest) GetIncludeClosed() bool {
	if m != nil {
		return m.IncludeClosed
	}
	return false
}

func (m *GetWorkflowsRequest) GetIncludeTasks() bool {
	if m != nil {
		return m.IncludeTasks
	}
	return false
}

type GetWorkflowsResponse struct {
	WorkflowsById        map[string]*GetWorkflowsResponse_Workflows `protobuf:"bytes,1,rep,name=workflows_by_id,json=workflowsById,proto3" json:"workflows_by_id,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *GetWorkflowsResponse) Reset()         { *m = GetWorkflowsResponse{} }
func (m *GetWorkflowsResponse) String() string { return proto.CompactTextString(m) }
func (*GetWorkflowsResponse) ProtoMessage()    {}
func (*GetWorkflowsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{2}
}
func (m *GetWorkflowsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkflowsResponse.Unmarshal(m, b)
}
func (m *GetWorkflowsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkflowsResponse.Marshal(b, m, deterministic)
}
func (dst *GetWorkflowsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkflowsResponse.Merge(dst, src)
}
func (m *GetWorkflowsResponse) XXX_Size() int {
	return xxx_messageInfo_GetWorkflowsResponse.Size(m)
}
func (m *GetWorkflowsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkflowsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkflowsResponse proto.InternalMessageInfo

func (m *GetWorkflowsResponse) GetWorkflowsById() map[string]*GetWorkflowsResponse_Workflows {
	if m != nil {
		return m.WorkflowsById
	}
	return nil
}

type GetWorkflowsResponse_Workflows struct {
	Workflows            []*model.Workflow `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetWorkflowsResponse_Workflows) Reset()         { *m = GetWorkflowsResponse_Workflows{} }
func (m *GetWorkflowsResponse_Workflows) String() string { return proto.CompactTextString(m) }
func (*GetWorkflowsResponse_Workflows) ProtoMessage()    {}
func (*GetWorkflowsResponse_Workflows) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{2, 0}
}
func (m *GetWorkflowsResponse_Workflows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkflowsResponse_Workflows.Unmarshal(m, b)
}
func (m *GetWorkflowsResponse_Workflows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkflowsResponse_Workflows.Marshal(b, m, deterministic)
}
func (dst *GetWorkflowsResponse_Workflows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkflowsResponse_Workflows.Merge(dst, src)
}
func (m *GetWorkflowsResponse_Workflows) XXX_Size() int {
	return xxx_messageInfo_GetWorkflowsResponse_Workflows.Size(m)
}
func (m *GetWorkflowsResponse_Workflows) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkflowsResponse_Workflows.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkflowsResponse_Workflows proto.InternalMessageInfo

func (m *GetWorkflowsResponse_Workflows) GetWorkflows() []*model.Workflow {
	if m != nil {
		return m.Workflows
	}
	return nil
}

type GetWorkflowStatusRequest struct {
	WorkflowId           string   `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	IncludeTasks         bool     `protobuf:"varint,2,opt,name=include_tasks,json=includeTasks,proto3" json:"include_tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWorkflowStatusRequest) Reset()         { *m = GetWorkflowStatusRequest{} }
func (m *GetWorkflowStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetWorkflowStatusRequest) ProtoMessage()    {}
func (*GetWorkflowStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{3}
}
func (m *GetWorkflowStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkflowStatusRequest.Unmarshal(m, b)
}
func (m *GetWorkflowStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkflowStatusRequest.Marshal(b, m, deterministic)
}
func (dst *GetWorkflowStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkflowStatusRequest.Merge(dst, src)
}
func (m *GetWorkflowStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetWorkflowStatusRequest.Size(m)
}
func (m *GetWorkflowStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkflowStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkflowStatusRequest proto.InternalMessageInfo

func (m *GetWorkflowStatusRequest) GetWorkflowId() string {
	if m != nil {
		return m.WorkflowId
	}
	return ""
}

func (m *GetWorkflowStatusRequest) GetIncludeTasks() bool {
	if m != nil {
		return m.IncludeTasks
	}
	return false
}

type GetWorkflowStatusResponse struct {
	Workflow             *model.Workflow `protobuf:"bytes,1,opt,name=workflow,proto3" json:"workflow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetWorkflowStatusResponse) Reset()         { *m = GetWorkflowStatusResponse{} }
func (m *GetWorkflowStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetWorkflowStatusResponse) ProtoMessage()    {}
func (*GetWorkflowStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{4}
}
func (m *GetWorkflowStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWorkflowStatusResponse.Unmarshal(m, b)
}
func (m *GetWorkflowStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWorkflowStatusResponse.Marshal(b, m, deterministic)
}
func (dst *GetWorkflowStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWorkflowStatusResponse.Merge(dst, src)
}
func (m *GetWorkflowStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetWorkflowStatusResponse.Size(m)
}
func (m *GetWorkflowStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWorkflowStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWorkflowStatusResponse proto.InternalMessageInfo

func (m *GetWorkflowStatusResponse) GetWorkflow() *model.Workflow {
	if m != nil {
		return m.Workflow
	}
	return nil
}

type RemoveWorkflowRequest struct {
	WorkflodId           string   `protobuf:"bytes,1,opt,name=workflod_id,json=workflodId,proto3" json:"workflod_id,omitempty"`
	ArchiveWorkflow      bool     `protobuf:"varint,2,opt,name=archive_workflow,json=archiveWorkflow,proto3" json:"archive_workflow,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveWorkflowRequest) Reset()         { *m = RemoveWorkflowRequest{} }
func (m *RemoveWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveWorkflowRequest) ProtoMessage()    {}
func (*RemoveWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{5}
}
func (m *RemoveWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveWorkflowRequest.Unmarshal(m, b)
}
func (m *RemoveWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveWorkflowRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveWorkflowRequest.Merge(dst, src)
}
func (m *RemoveWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveWorkflowRequest.Size(m)
}
func (m *RemoveWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveWorkflowRequest proto.InternalMessageInfo

func (m *RemoveWorkflowRequest) GetWorkflodId() string {
	if m != nil {
		return m.WorkflodId
	}
	return ""
}

func (m *RemoveWorkflowRequest) GetArchiveWorkflow() bool {
	if m != nil {
		return m.ArchiveWorkflow
	}
	return false
}

type RemoveWorkflowResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveWorkflowResponse) Reset()         { *m = RemoveWorkflowResponse{} }
func (m *RemoveWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveWorkflowResponse) ProtoMessage()    {}
func (*RemoveWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{6}
}
func (m *RemoveWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveWorkflowResponse.Unmarshal(m, b)
}
func (m *RemoveWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveWorkflowResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveWorkflowResponse.Merge(dst, src)
}
func (m *RemoveWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveWorkflowResponse.Size(m)
}
func (m *RemoveWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveWorkflowResponse proto.InternalMessageInfo

type GetRunningWorkflowsRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              int32    `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	StartTime            int64    `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64    `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRunningWorkflowsRequest) Reset()         { *m = GetRunningWorkflowsRequest{} }
func (m *GetRunningWorkflowsRequest) String() string { return proto.CompactTextString(m) }
func (*GetRunningWorkflowsRequest) ProtoMessage()    {}
func (*GetRunningWorkflowsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{7}
}
func (m *GetRunningWorkflowsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRunningWorkflowsRequest.Unmarshal(m, b)
}
func (m *GetRunningWorkflowsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRunningWorkflowsRequest.Marshal(b, m, deterministic)
}
func (dst *GetRunningWorkflowsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRunningWorkflowsRequest.Merge(dst, src)
}
func (m *GetRunningWorkflowsRequest) XXX_Size() int {
	return xxx_messageInfo_GetRunningWorkflowsRequest.Size(m)
}
func (m *GetRunningWorkflowsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRunningWorkflowsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRunningWorkflowsRequest proto.InternalMessageInfo

func (m *GetRunningWorkflowsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetRunningWorkflowsRequest) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *GetRunningWorkflowsRequest) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *GetRunningWorkflowsRequest) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type GetRunningWorkflowsResponse struct {
	WorkflowIds          []string `protobuf:"bytes,1,rep,name=workflow_ids,json=workflowIds,proto3" json:"workflow_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRunningWorkflowsResponse) Reset()         { *m = GetRunningWorkflowsResponse{} }
func (m *GetRunningWorkflowsResponse) String() string { return proto.CompactTextString(m) }
func (*GetRunningWorkflowsResponse) ProtoMessage()    {}
func (*GetRunningWorkflowsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{8}
}
func (m *GetRunningWorkflowsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRunningWorkflowsResponse.Unmarshal(m, b)
}
func (m *GetRunningWorkflowsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRunningWorkflowsResponse.Marshal(b, m, deterministic)
}
func (dst *GetRunningWorkflowsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRunningWorkflowsResponse.Merge(dst, src)
}
func (m *GetRunningWorkflowsResponse) XXX_Size() int {
	return xxx_messageInfo_GetRunningWorkflowsResponse.Size(m)
}
func (m *GetRunningWorkflowsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRunningWorkflowsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRunningWorkflowsResponse proto.InternalMessageInfo

func (m *GetRunningWorkflowsResponse) GetWorkflowIds() []string {
	if m != nil {
		return m.WorkflowIds
	}
	return nil
}

type DecideWorkflowRequest struct {
	WorkflowId           string   `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecideWorkflowRequest) Reset()         { *m = DecideWorkflowRequest{} }
func (m *DecideWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*DecideWorkflowRequest) ProtoMessage()    {}
func (*DecideWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{9}
}
func (m *DecideWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecideWorkflowRequest.Unmarshal(m, b)
}
func (m *DecideWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecideWorkflowRequest.Marshal(b, m, deterministic)
}
func (dst *DecideWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecideWorkflowRequest.Merge(dst, src)
}
func (m *DecideWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_DecideWorkflowRequest.Size(m)
}
func (m *DecideWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecideWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecideWorkflowRequest proto.InternalMessageInfo

func (m *DecideWorkflowRequest) GetWorkflowId() string {
	if m != nil {
		return m.WorkflowId
	}
	return ""
}

type DecideWorkflowResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecideWorkflowResponse) Reset()         { *m = DecideWorkflowResponse{} }
func (m *DecideWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*DecideWorkflowResponse) ProtoMessage()    {}
func (*DecideWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{10}
}
func (m *DecideWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecideWorkflowResponse.Unmarshal(m, b)
}
func (m *DecideWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecideWorkflowResponse.Marshal(b, m, deterministic)
}
func (dst *DecideWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecideWorkflowResponse.Merge(dst, src)
}
func (m *DecideWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_DecideWorkflowResponse.Size(m)
}
func (m *DecideWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DecideWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DecideWorkflowResponse proto.InternalMessageInfo

type PauseWorkflowRequest struct {
	WorkflowId           string   `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PauseWorkflowRequest) Reset()         { *m = PauseWorkflowRequest{} }
func (m *PauseWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*PauseWorkflowRequest) ProtoMessage()    {}
func (*PauseWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{11}
}
func (m *PauseWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PauseWorkflowRequest.Unmarshal(m, b)
}
func (m *PauseWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PauseWorkflowRequest.Marshal(b, m, deterministic)
}
func (dst *PauseWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PauseWorkflowRequest.Merge(dst, src)
}
func (m *PauseWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_PauseWorkflowRequest.Size(m)
}
func (m *PauseWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PauseWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PauseWorkflowRequest proto.InternalMessageInfo

func (m *PauseWorkflowRequest) GetWorkflowId() string {
	if m != nil {
		return m.WorkflowId
	}
	return ""
}

type PauseWorkflowResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PauseWorkflowResponse) Reset()         { *m = PauseWorkflowResponse{} }
func (m *PauseWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*PauseWorkflowResponse) ProtoMessage()    {}
func (*PauseWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{12}
}
func (m *PauseWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PauseWorkflowResponse.Unmarshal(m, b)
}
func (m *PauseWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PauseWorkflowResponse.Marshal(b, m, deterministic)
}
func (dst *PauseWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PauseWorkflowResponse.Merge(dst, src)
}
func (m *PauseWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_PauseWorkflowResponse.Size(m)
}
func (m *PauseWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PauseWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PauseWorkflowResponse proto.InternalMessageInfo

type ResumeWorkflowRequest struct {
	WorkflowId           string   `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResumeWorkflowRequest) Reset()         { *m = ResumeWorkflowRequest{} }
func (m *ResumeWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*ResumeWorkflowRequest) ProtoMessage()    {}
func (*ResumeWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{13}
}
func (m *ResumeWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResumeWorkflowRequest.Unmarshal(m, b)
}
func (m *ResumeWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResumeWorkflowRequest.Marshal(b, m, deterministic)
}
func (dst *ResumeWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResumeWorkflowRequest.Merge(dst, src)
}
func (m *ResumeWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_ResumeWorkflowRequest.Size(m)
}
func (m *ResumeWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResumeWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResumeWorkflowRequest proto.InternalMessageInfo

func (m *ResumeWorkflowRequest) GetWorkflowId() string {
	if m != nil {
		return m.WorkflowId
	}
	return ""
}

type ResumeWorkflowResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResumeWorkflowResponse) Reset()         { *m = ResumeWorkflowResponse{} }
func (m *ResumeWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*ResumeWorkflowResponse) ProtoMessage()    {}
func (*ResumeWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{14}
}
func (m *ResumeWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResumeWorkflowResponse.Unmarshal(m, b)
}
func (m *ResumeWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResumeWorkflowResponse.Marshal(b, m, deterministic)
}
func (dst *ResumeWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResumeWorkflowResponse.Merge(dst, src)
}
func (m *ResumeWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_ResumeWorkflowResponse.Size(m)
}
func (m *ResumeWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResumeWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResumeWorkflowResponse proto.InternalMessageInfo

type SkipTaskRequest struct {
	WorkflowId           string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TaskReferenceName    string                 `protobuf:"bytes,2,opt,name=task_reference_name,json=taskReferenceName,proto3" json:"task_reference_name,omitempty"`
	Request              *model.SkipTaskRequest `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *SkipTaskRequest) Reset()         { *m = SkipTaskRequest{} }
func (m *SkipTaskRequest) String() string { return proto.CompactTextString(m) }
func (*SkipTaskRequest) ProtoMessage()    {}
func (*SkipTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{15}
}
func (m *SkipTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkipTaskRequest.Unmarshal(m, b)
}
func (m *SkipTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkipTaskRequest.Marshal(b, m, deterministic)
}
func (dst *SkipTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkipTaskRequest.Merge(dst, src)
}
func (m *SkipTaskRequest) XXX_Size() int {
	return xxx_messageInfo_SkipTaskRequest.Size(m)
}
func (m *SkipTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SkipTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SkipTaskRequest proto.InternalMessageInfo

func (m *SkipTaskRequest) GetWorkflowId() string {
	if m != nil {
		return m.WorkflowId
	}
	return ""
}

func (m *SkipTaskRequest) GetTaskReferenceName() string {
	if m != nil {
		return m.TaskReferenceName
	}
	return ""
}

func (m *SkipTaskRequest) GetRequest() *model.SkipTaskRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

type SkipTaskResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SkipTaskResponse) Reset()         { *m = SkipTaskResponse{} }
func (m *SkipTaskResponse) String() string { return proto.CompactTextString(m) }
func (*SkipTaskResponse) ProtoMessage()    {}
func (*SkipTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{16}
}
func (m *SkipTaskResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SkipTaskResponse.Unmarshal(m, b)
}
func (m *SkipTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SkipTaskResponse.Marshal(b, m, deterministic)
}
func (dst *SkipTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SkipTaskResponse.Merge(dst, src)
}
func (m *SkipTaskResponse) XXX_Size() int {
	return xxx_messageInfo_SkipTaskResponse.Size(m)
}
func (m *SkipTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SkipTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SkipTaskResponse proto.InternalMessageInfo

type RerunWorkflowResponse struct {
	WorkflowId           string   `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RerunWorkflowResponse) Reset()         { *m = RerunWorkflowResponse{} }
func (m *RerunWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*RerunWorkflowResponse) ProtoMessage()    {}
func (*RerunWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{17}
}
func (m *RerunWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RerunWorkflowResponse.Unmarshal(m, b)
}
func (m *RerunWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RerunWorkflowResponse.Marshal(b, m, deterministic)
}
func (dst *RerunWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RerunWorkflowResponse.Merge(dst, src)
}
func (m *RerunWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_RerunWorkflowResponse.Size(m)
}
func (m *RerunWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RerunWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RerunWorkflowResponse proto.InternalMessageInfo

func (m *RerunWorkflowResponse) GetWorkflowId() string {
	if m != nil {
		return m.WorkflowId
	}
	return ""
}

type RestartWorkflowRequest struct {
	WorkflowId           string   `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	UseLatestDefinitions bool     `protobuf:"varint,2,opt,name=use_latest_definitions,json=useLatestDefinitions,proto3" json:"use_latest_definitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestartWorkflowRequest) Reset()         { *m = RestartWorkflowRequest{} }
func (m *RestartWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*RestartWorkflowRequest) ProtoMessage()    {}
func (*RestartWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{18}
}
func (m *RestartWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestartWorkflowRequest.Unmarshal(m, b)
}
func (m *RestartWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestartWorkflowRequest.Marshal(b, m, deterministic)
}
func (dst *RestartWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestartWorkflowRequest.Merge(dst, src)
}
func (m *RestartWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_RestartWorkflowRequest.Size(m)
}
func (m *RestartWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestartWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestartWorkflowRequest proto.InternalMessageInfo

func (m *RestartWorkflowRequest) GetWorkflowId() string {
	if m != nil {
		return m.WorkflowId
	}
	return ""
}

func (m *RestartWorkflowRequest) GetUseLatestDefinitions() bool {
	if m != nil {
		return m.UseLatestDefinitions
	}
	return false
}

type RestartWorkflowResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestartWorkflowResponse) Reset()         { *m = RestartWorkflowResponse{} }
func (m *RestartWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*RestartWorkflowResponse) ProtoMessage()    {}
func (*RestartWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{19}
}
func (m *RestartWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestartWorkflowResponse.Unmarshal(m, b)
}
func (m *RestartWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestartWorkflowResponse.Marshal(b, m, deterministic)
}
func (dst *RestartWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestartWorkflowResponse.Merge(dst, src)
}
func (m *RestartWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_RestartWorkflowResponse.Size(m)
}
func (m *RestartWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestartWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestartWorkflowResponse proto.InternalMessageInfo

type RetryWorkflowRequest struct {
	WorkflowId           string   `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetryWorkflowRequest) Reset()         { *m = RetryWorkflowRequest{} }
func (m *RetryWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*RetryWorkflowRequest) ProtoMessage()    {}
func (*RetryWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{20}
}
func (m *RetryWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryWorkflowRequest.Unmarshal(m, b)
}
func (m *RetryWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryWorkflowRequest.Marshal(b, m, deterministic)
}
func (dst *RetryWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryWorkflowRequest.Merge(dst, src)
}
func (m *RetryWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_RetryWorkflowRequest.Size(m)
}
func (m *RetryWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetryWorkflowRequest proto.InternalMessageInfo

func (m *RetryWorkflowRequest) GetWorkflowId() string {
	if m != nil {
		return m.WorkflowId
	}
	return ""
}

type RetryWorkflowResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetryWorkflowResponse) Reset()         { *m = RetryWorkflowResponse{} }
func (m *RetryWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*RetryWorkflowResponse) ProtoMessage()    {}
func (*RetryWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{21}
}
func (m *RetryWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryWorkflowResponse.Unmarshal(m, b)
}
func (m *RetryWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryWorkflowResponse.Marshal(b, m, deterministic)
}
func (dst *RetryWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryWorkflowResponse.Merge(dst, src)
}
func (m *RetryWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_RetryWorkflowResponse.Size(m)
}
func (m *RetryWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetryWorkflowResponse proto.InternalMessageInfo

type ResetWorkflowCallbacksRequest struct {
	WorkflowId           string   `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetWorkflowCallbacksRequest) Reset()         { *m = ResetWorkflowCallbacksRequest{} }
func (m *ResetWorkflowCallbacksRequest) String() string { return proto.CompactTextString(m) }
func (*ResetWorkflowCallbacksRequest) ProtoMessage()    {}
func (*ResetWorkflowCallbacksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{22}
}
func (m *ResetWorkflowCallbacksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetWorkflowCallbacksRequest.Unmarshal(m, b)
}
func (m *ResetWorkflowCallbacksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetWorkflowCallbacksRequest.Marshal(b, m, deterministic)
}
func (dst *ResetWorkflowCallbacksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetWorkflowCallbacksRequest.Merge(dst, src)
}
func (m *ResetWorkflowCallbacksRequest) XXX_Size() int {
	return xxx_messageInfo_ResetWorkflowCallbacksRequest.Size(m)
}
func (m *ResetWorkflowCallbacksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetWorkflowCallbacksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetWorkflowCallbacksRequest proto.InternalMessageInfo

func (m *ResetWorkflowCallbacksRequest) GetWorkflowId() string {
	if m != nil {
		return m.WorkflowId
	}
	return ""
}

type ResetWorkflowCallbacksResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetWorkflowCallbacksResponse) Reset()         { *m = ResetWorkflowCallbacksResponse{} }
func (m *ResetWorkflowCallbacksResponse) String() string { return proto.CompactTextString(m) }
func (*ResetWorkflowCallbacksResponse) ProtoMessage()    {}
func (*ResetWorkflowCallbacksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{23}
}
func (m *ResetWorkflowCallbacksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetWorkflowCallbacksResponse.Unmarshal(m, b)
}
func (m *ResetWorkflowCallbacksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetWorkflowCallbacksResponse.Marshal(b, m, deterministic)
}
func (dst *ResetWorkflowCallbacksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetWorkflowCallbacksResponse.Merge(dst, src)
}
func (m *ResetWorkflowCallbacksResponse) XXX_Size() int {
	return xxx_messageInfo_ResetWorkflowCallbacksResponse.Size(m)
}
func (m *ResetWorkflowCallbacksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetWorkflowCallbacksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetWorkflowCallbacksResponse proto.InternalMessageInfo

type TerminateWorkflowRequest struct {
	WorkflowId           string   `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Reason               string   `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TerminateWorkflowRequest) Reset()         { *m = TerminateWorkflowRequest{} }
func (m *TerminateWorkflowRequest) String() string { return proto.CompactTextString(m) }
func (*TerminateWorkflowRequest) ProtoMessage()    {}
func (*TerminateWorkflowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{24}
}
func (m *TerminateWorkflowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminateWorkflowRequest.Unmarshal(m, b)
}
func (m *TerminateWorkflowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminateWorkflowRequest.Marshal(b, m, deterministic)
}
func (dst *TerminateWorkflowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminateWorkflowRequest.Merge(dst, src)
}
func (m *TerminateWorkflowRequest) XXX_Size() int {
	return xxx_messageInfo_TerminateWorkflowRequest.Size(m)
}
func (m *TerminateWorkflowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminateWorkflowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TerminateWorkflowRequest proto.InternalMessageInfo

func (m *TerminateWorkflowRequest) GetWorkflowId() string {
	if m != nil {
		return m.WorkflowId
	}
	return ""
}

func (m *TerminateWorkflowRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type TerminateWorkflowResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TerminateWorkflowResponse) Reset()         { *m = TerminateWorkflowResponse{} }
func (m *TerminateWorkflowResponse) String() string { return proto.CompactTextString(m) }
func (*TerminateWorkflowResponse) ProtoMessage()    {}
func (*TerminateWorkflowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{25}
}
func (m *TerminateWorkflowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminateWorkflowResponse.Unmarshal(m, b)
}
func (m *TerminateWorkflowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminateWorkflowResponse.Marshal(b, m, deterministic)
}
func (dst *TerminateWorkflowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminateWorkflowResponse.Merge(dst, src)
}
func (m *TerminateWorkflowResponse) XXX_Size() int {
	return xxx_messageInfo_TerminateWorkflowResponse.Size(m)
}
func (m *TerminateWorkflowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminateWorkflowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TerminateWorkflowResponse proto.InternalMessageInfo

type WorkflowSummarySearchResult struct {
	TotalHits            int64                    `protobuf:"varint,1,opt,name=total_hits,json=totalHits,proto3" json:"total_hits,omitempty"`
	Results              []*model.WorkflowSummary `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *WorkflowSummarySearchResult) Reset()         { *m = WorkflowSummarySearchResult{} }
func (m *WorkflowSummarySearchResult) String() string { return proto.CompactTextString(m) }
func (*WorkflowSummarySearchResult) ProtoMessage()    {}
func (*WorkflowSummarySearchResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_workflow_service_f78a771ea5b8eb25, []int{26}
}
func (m *WorkflowSummarySearchResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkflowSummarySearchResult.Unmarshal(m, b)
}
func (m *WorkflowSummarySearchResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkflowSummarySearchResult.Marshal(b, m, deterministic)
}
func (dst *WorkflowSummarySearchResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkflowSummarySearchResult.Merge(dst, src)
}
func (m *WorkflowSummarySearchResult) XXX_Size() int {
	return xxx_messageInfo_WorkflowSummarySearchResult.Size(m)
}
func (m *WorkflowSummarySearchResult) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkflowSummarySearchResult.DiscardUnknown(m)
}

var xxx_messageInfo_WorkflowSummarySearchResult proto.InternalMessageInfo

func (m *WorkflowSummarySearchResult) GetTotalHits() int64 {
	if m != nil {
		return m.TotalHits
	}
	return 0
}

func (m *WorkflowSummarySearchResult) GetResults() []*model.WorkflowSummary {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterType((*StartWorkflowResponse)(nil), "conductor.grpc.workflows.StartWorkflowResponse")
	proto.RegisterType((*GetWorkflowsRequest)(nil), "conductor.grpc.workflows.GetWorkflowsRequest")
	proto.RegisterType((*GetWorkflowsResponse)(nil), "conductor.grpc.workflows.GetWorkflowsResponse")
	proto.RegisterMapType((map[string]*GetWorkflowsResponse_Workflows)(nil), "conductor.grpc.workflows.GetWorkflowsResponse.WorkflowsByIdEntry")
	proto.RegisterType((*GetWorkflowsResponse_Workflows)(nil), "conductor.grpc.workflows.GetWorkflowsResponse.Workflows")
	proto.RegisterType((*GetWorkflowStatusRequest)(nil), "conductor.grpc.workflows.GetWorkflowStatusRequest")
	proto.RegisterType((*GetWorkflowStatusResponse)(nil), "conductor.grpc.workflows.GetWorkflowStatusResponse")
	proto.RegisterType((*RemoveWorkflowRequest)(nil), "conductor.grpc.workflows.RemoveWorkflowRequest")
	proto.RegisterType((*RemoveWorkflowResponse)(nil), "conductor.grpc.workflows.RemoveWorkflowResponse")
	proto.RegisterType((*GetRunningWorkflowsRequest)(nil), "conductor.grpc.workflows.GetRunningWorkflowsRequest")
	proto.RegisterType((*GetRunningWorkflowsResponse)(nil), "conductor.grpc.workflows.GetRunningWorkflowsResponse")
	proto.RegisterType((*DecideWorkflowRequest)(nil), "conductor.grpc.workflows.DecideWorkflowRequest")
	proto.RegisterType((*DecideWorkflowResponse)(nil), "conductor.grpc.workflows.DecideWorkflowResponse")
	proto.RegisterType((*PauseWorkflowRequest)(nil), "conductor.grpc.workflows.PauseWorkflowRequest")
	proto.RegisterType((*PauseWorkflowResponse)(nil), "conductor.grpc.workflows.PauseWorkflowResponse")
	proto.RegisterType((*ResumeWorkflowRequest)(nil), "conductor.grpc.workflows.ResumeWorkflowRequest")
	proto.RegisterType((*ResumeWorkflowResponse)(nil), "conductor.grpc.workflows.ResumeWorkflowResponse")
	proto.RegisterType((*SkipTaskRequest)(nil), "conductor.grpc.workflows.SkipTaskRequest")
	proto.RegisterType((*SkipTaskResponse)(nil), "conductor.grpc.workflows.SkipTaskResponse")
	proto.RegisterType((*RerunWorkflowResponse)(nil), "conductor.grpc.workflows.RerunWorkflowResponse")
	proto.RegisterType((*RestartWorkflowRequest)(nil), "conductor.grpc.workflows.RestartWorkflowRequest")
	proto.RegisterType((*RestartWorkflowResponse)(nil), "conductor.grpc.workflows.RestartWorkflowResponse")
	proto.RegisterType((*RetryWorkflowRequest)(nil), "conductor.grpc.workflows.RetryWorkflowRequest")
	proto.RegisterType((*RetryWorkflowResponse)(nil), "conductor.grpc.workflows.RetryWorkflowResponse")
	proto.RegisterType((*ResetWorkflowCallbacksRequest)(nil), "conductor.grpc.workflows.ResetWorkflowCallbacksRequest")
	proto.RegisterType((*ResetWorkflowCallbacksResponse)(nil), "conductor.grpc.workflows.ResetWorkflowCallbacksResponse")
	proto.RegisterType((*TerminateWorkflowRequest)(nil), "conductor.grpc.workflows.TerminateWorkflowRequest")
	proto.RegisterType((*TerminateWorkflowResponse)(nil), "conductor.grpc.workflows.TerminateWorkflowResponse")
	proto.RegisterType((*WorkflowSummarySearchResult)(nil), "conductor.grpc.workflows.WorkflowSummarySearchResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WorkflowServiceClient is the client API for WorkflowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WorkflowServiceClient interface {
	// POST /
	StartWorkflow(ctx context.Context, in *model.StartWorkflowRequest, opts ...grpc.CallOption) (*StartWorkflowResponse, error)
	// GET /{name}/correlated/{correlationId}
	GetWorkflows(ctx context.Context, in *GetWorkflowsRequest, opts ...grpc.CallOption) (*GetWorkflowsResponse, error)
	// GET /{workflowId}
	GetWorkflowStatus(ctx context.Context, in *GetWorkflowStatusRequest, opts ...grpc.CallOption) (*model.Workflow, error)
	// DELETE /{workflodId}/remove
	RemoveWorkflow(ctx context.Context, in *RemoveWorkflowRequest, opts ...grpc.CallOption) (*RemoveWorkflowResponse, error)
	// GET /running/{name}
	GetRunningWorkflows(ctx context.Context, in *GetRunningWorkflowsRequest, opts ...grpc.CallOption) (*GetRunningWorkflowsResponse, error)
	// PUT /decide/{workflowId}
	DecideWorkflow(ctx context.Context, in *DecideWorkflowRequest, opts ...grpc.CallOption) (*DecideWorkflowResponse, error)
	// PUT /{workflowId}/pause
	PauseWorkflow(ctx context.Context, in *PauseWorkflowRequest, opts ...grpc.CallOption) (*PauseWorkflowResponse, error)
	// PUT /{workflowId}/pause
	ResumeWorkflow(ctx context.Context, in *ResumeWorkflowRequest, opts ...grpc.CallOption) (*ResumeWorkflowResponse, error)
	// PUT /{workflowId}/skiptask/{taskReferenceName}
	SkipTaskFromWorkflow(ctx context.Context, in *SkipTaskRequest, opts ...grpc.CallOption) (*SkipTaskResponse, error)
	// POST /{workflowId}/rerun
	RerunWorkflow(ctx context.Context, in *model.RerunWorkflowRequest, opts ...grpc.CallOption) (*RerunWorkflowResponse, error)
	// POST /{workflowId}/restart
	RestartWorkflow(ctx context.Context, in *RestartWorkflowRequest, opts ...grpc.CallOption) (*RestartWorkflowResponse, error)
	// POST /{workflowId}retry
	RetryWorkflow(ctx context.Context, in *RetryWorkflowRequest, opts ...grpc.CallOption) (*RetryWorkflowResponse, error)
	// POST /{workflowId}/resetcallbacks
	ResetWorkflowCallbacks(ctx context.Context, in *ResetWorkflowCallbacksRequest, opts ...grpc.CallOption) (*ResetWorkflowCallbacksResponse, error)
	// DELETE /{workflowId}
	TerminateWorkflow(ctx context.Context, in *TerminateWorkflowRequest, opts ...grpc.CallOption) (*TerminateWorkflowResponse, error)
	// GET /search
	Search(ctx context.Context, in *search.Request, opts ...grpc.CallOption) (*WorkflowSummarySearchResult, error)
	SearchByTasks(ctx context.Context, in *search.Request, opts ...grpc.CallOption) (*WorkflowSummarySearchResult, error)
}

type workflowServiceClient struct {
	cc *grpc.ClientConn
}

func NewWorkflowServiceClient(cc *grpc.ClientConn) WorkflowServiceClient {
	return &workflowServiceClient{cc}
}

func (c *workflowServiceClient) StartWorkflow(ctx context.Context, in *model.StartWorkflowRequest, opts ...grpc.CallOption) (*StartWorkflowResponse, error) {
	out := new(StartWorkflowResponse)
	err := c.cc.Invoke(ctx, "/conductor.grpc.workflows.WorkflowService/StartWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetWorkflows(ctx context.Context, in *GetWorkflowsRequest, opts ...grpc.CallOption) (*GetWorkflowsResponse, error) {
	out := new(GetWorkflowsResponse)
	err := c.cc.Invoke(ctx, "/conductor.grpc.workflows.WorkflowService/GetWorkflows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetWorkflowStatus(ctx context.Context, in *GetWorkflowStatusRequest, opts ...grpc.CallOption) (*model.Workflow, error) {
	out := new(model.Workflow)
	err := c.cc.Invoke(ctx, "/conductor.grpc.workflows.WorkflowService/GetWorkflowStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) RemoveWorkflow(ctx context.Context, in *RemoveWorkflowRequest, opts ...grpc.CallOption) (*RemoveWorkflowResponse, error) {
	out := new(RemoveWorkflowResponse)
	err := c.cc.Invoke(ctx, "/conductor.grpc.workflows.WorkflowService/RemoveWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetRunningWorkflows(ctx context.Context, in *GetRunningWorkflowsRequest, opts ...grpc.CallOption) (*GetRunningWorkflowsResponse, error) {
	out := new(GetRunningWorkflowsResponse)
	err := c.cc.Invoke(ctx, "/conductor.grpc.workflows.WorkflowService/GetRunningWorkflows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) DecideWorkflow(ctx context.Context, in *DecideWorkflowRequest, opts ...grpc.CallOption) (*DecideWorkflowResponse, error) {
	out := new(DecideWorkflowResponse)
	err := c.cc.Invoke(ctx, "/conductor.grpc.workflows.WorkflowService/DecideWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) PauseWorkflow(ctx context.Context, in *PauseWorkflowRequest, opts ...grpc.CallOption) (*PauseWorkflowResponse, error) {
	out := new(PauseWorkflowResponse)
	err := c.cc.Invoke(ctx, "/conductor.grpc.workflows.WorkflowService/PauseWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ResumeWorkflow(ctx context.Context, in *ResumeWorkflowRequest, opts ...grpc.CallOption) (*ResumeWorkflowResponse, error) {
	out := new(ResumeWorkflowResponse)
	err := c.cc.Invoke(ctx, "/conductor.grpc.workflows.WorkflowService/ResumeWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) SkipTaskFromWorkflow(ctx context.Context, in *SkipTaskRequest, opts ...grpc.CallOption) (*SkipTaskResponse, error) {
	out := new(SkipTaskResponse)
	err := c.cc.Invoke(ctx, "/conductor.grpc.workflows.WorkflowService/SkipTaskFromWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) RerunWorkflow(ctx context.Context, in *model.RerunWorkflowRequest, opts ...grpc.CallOption) (*RerunWorkflowResponse, error) {
	out := new(RerunWorkflowResponse)
	err := c.cc.Invoke(ctx, "/conductor.grpc.workflows.WorkflowService/RerunWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) RestartWorkflow(ctx context.Context, in *RestartWorkflowRequest, opts ...grpc.CallOption) (*RestartWorkflowResponse, error) {
	out := new(RestartWorkflowResponse)
	err := c.cc.Invoke(ctx, "/conductor.grpc.workflows.WorkflowService/RestartWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) RetryWorkflow(ctx context.Context, in *RetryWorkflowRequest, opts ...grpc.CallOption) (*RetryWorkflowResponse, error) {
	out := new(RetryWorkflowResponse)
	err := c.cc.Invoke(ctx, "/conductor.grpc.workflows.WorkflowService/RetryWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ResetWorkflowCallbacks(ctx context.Context, in *ResetWorkflowCallbacksRequest, opts ...grpc.CallOption) (*ResetWorkflowCallbacksResponse, error) {
	out := new(ResetWorkflowCallbacksResponse)
	err := c.cc.Invoke(ctx, "/conductor.grpc.workflows.WorkflowService/ResetWorkflowCallbacks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) TerminateWorkflow(ctx context.Context, in *TerminateWorkflowRequest, opts ...grpc.CallOption) (*TerminateWorkflowResponse, error) {
	out := new(TerminateWorkflowResponse)
	err := c.cc.Invoke(ctx, "/conductor.grpc.workflows.WorkflowService/TerminateWorkflow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) Search(ctx context.Context, in *search.Request, opts ...grpc.CallOption) (*WorkflowSummarySearchResult, error) {
	out := new(WorkflowSummarySearchResult)
	err := c.cc.Invoke(ctx, "/conductor.grpc.workflows.WorkflowService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) SearchByTasks(ctx context.Context, in *search.Request, opts ...grpc.CallOption) (*WorkflowSummarySearchResult, error) {
	out := new(WorkflowSummarySearchResult)
	err := c.cc.Invoke(ctx, "/conductor.grpc.workflows.WorkflowService/SearchByTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowServiceServer is the server API for WorkflowService service.
type WorkflowServiceServer interface {
	// POST /
	StartWorkflow(context.Context, *model.StartWorkflowRequest) (*StartWorkflowResponse, error)
	// GET /{name}/correlated/{correlationId}
	GetWorkflows(context.Context, *GetWorkflowsRequest) (*GetWorkflowsResponse, error)
	// GET /{workflowId}
	GetWorkflowStatus(context.Context, *GetWorkflowStatusRequest) (*model.Workflow, error)
	// DELETE /{workflodId}/remove
	RemoveWorkflow(context.Context, *RemoveWorkflowRequest) (*RemoveWorkflowResponse, error)
	// GET /running/{name}
	GetRunningWorkflows(context.Context, *GetRunningWorkflowsRequest) (*GetRunningWorkflowsResponse, error)
	// PUT /decide/{workflowId}
	DecideWorkflow(context.Context, *DecideWorkflowRequest) (*DecideWorkflowResponse, error)
	// PUT /{workflowId}/pause
	PauseWorkflow(context.Context, *PauseWorkflowRequest) (*PauseWorkflowResponse, error)
	// PUT /{workflowId}/pause
	ResumeWorkflow(context.Context, *ResumeWorkflowRequest) (*ResumeWorkflowResponse, error)
	// PUT /{workflowId}/skiptask/{taskReferenceName}
	SkipTaskFromWorkflow(context.Context, *SkipTaskRequest) (*SkipTaskResponse, error)
	// POST /{workflowId}/rerun
	RerunWorkflow(context.Context, *model.RerunWorkflowRequest) (*RerunWorkflowResponse, error)
	// POST /{workflowId}/restart
	RestartWorkflow(context.Context, *RestartWorkflowRequest) (*RestartWorkflowResponse, error)
	// POST /{workflowId}retry
	RetryWorkflow(context.Context, *RetryWorkflowRequest) (*RetryWorkflowResponse, error)
	// POST /{workflowId}/resetcallbacks
	ResetWorkflowCallbacks(context.Context, *ResetWorkflowCallbacksRequest) (*ResetWorkflowCallbacksResponse, error)
	// DELETE /{workflowId}
	TerminateWorkflow(context.Context, *TerminateWorkflowRequest) (*TerminateWorkflowResponse, error)
	// GET /search
	Search(context.Context, *search.Request) (*WorkflowSummarySearchResult, error)
	SearchByTasks(context.Context, *search.Request) (*WorkflowSummarySearchResult, error)
}

func RegisterWorkflowServiceServer(s *grpc.Server, srv WorkflowServiceServer) {
	s.RegisterService(&_WorkflowService_serviceDesc, srv)
}

func _WorkflowService_StartWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.StartWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).StartWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductor.grpc.workflows.WorkflowService/StartWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).StartWorkflow(ctx, req.(*model.StartWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductor.grpc.workflows.WorkflowService/GetWorkflows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetWorkflows(ctx, req.(*GetWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetWorkflowStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetWorkflowStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductor.grpc.workflows.WorkflowService/GetWorkflowStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetWorkflowStatus(ctx, req.(*GetWorkflowStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_RemoveWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).RemoveWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductor.grpc.workflows.WorkflowService/RemoveWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).RemoveWorkflow(ctx, req.(*RemoveWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetRunningWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunningWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetRunningWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductor.grpc.workflows.WorkflowService/GetRunningWorkflows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetRunningWorkflows(ctx, req.(*GetRunningWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_DecideWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecideWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).DecideWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductor.grpc.workflows.WorkflowService/DecideWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).DecideWorkflow(ctx, req.(*DecideWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_PauseWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).PauseWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductor.grpc.workflows.WorkflowService/PauseWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).PauseWorkflow(ctx, req.(*PauseWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ResumeWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ResumeWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductor.grpc.workflows.WorkflowService/ResumeWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ResumeWorkflow(ctx, req.(*ResumeWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_SkipTaskFromWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SkipTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).SkipTaskFromWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductor.grpc.workflows.WorkflowService/SkipTaskFromWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).SkipTaskFromWorkflow(ctx, req.(*SkipTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_RerunWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(model.RerunWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).RerunWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductor.grpc.workflows.WorkflowService/RerunWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).RerunWorkflow(ctx, req.(*model.RerunWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_RestartWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).RestartWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductor.grpc.workflows.WorkflowService/RestartWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).RestartWorkflow(ctx, req.(*RestartWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_RetryWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).RetryWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductor.grpc.workflows.WorkflowService/RetryWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).RetryWorkflow(ctx, req.(*RetryWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ResetWorkflowCallbacks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetWorkflowCallbacksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ResetWorkflowCallbacks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductor.grpc.workflows.WorkflowService/ResetWorkflowCallbacks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ResetWorkflowCallbacks(ctx, req.(*ResetWorkflowCallbacksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_TerminateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).TerminateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductor.grpc.workflows.WorkflowService/TerminateWorkflow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).TerminateWorkflow(ctx, req.(*TerminateWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(search.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductor.grpc.workflows.WorkflowService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).Search(ctx, req.(*search.Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_SearchByTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(search.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).SearchByTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conductor.grpc.workflows.WorkflowService/SearchByTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).SearchByTasks(ctx, req.(*search.Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _WorkflowService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "conductor.grpc.workflows.WorkflowService",
	HandlerType: (*WorkflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartWorkflow",
			Handler:    _WorkflowService_StartWorkflow_Handler,
		},
		{
			MethodName: "GetWorkflows",
			Handler:    _WorkflowService_GetWorkflows_Handler,
		},
		{
			MethodName: "GetWorkflowStatus",
			Handler:    _WorkflowService_GetWorkflowStatus_Handler,
		},
		{
			MethodName: "RemoveWorkflow",
			Handler:    _WorkflowService_RemoveWorkflow_Handler,
		},
		{
			MethodName: "GetRunningWorkflows",
			Handler:    _WorkflowService_GetRunningWorkflows_Handler,
		},
		{
			MethodName: "DecideWorkflow",
			Handler:    _WorkflowService_DecideWorkflow_Handler,
		},
		{
			MethodName: "PauseWorkflow",
			Handler:    _WorkflowService_PauseWorkflow_Handler,
		},
		{
			MethodName: "ResumeWorkflow",
			Handler:    _WorkflowService_ResumeWorkflow_Handler,
		},
		{
			MethodName: "SkipTaskFromWorkflow",
			Handler:    _WorkflowService_SkipTaskFromWorkflow_Handler,
		},
		{
			MethodName: "RerunWorkflow",
			Handler:    _WorkflowService_RerunWorkflow_Handler,
		},
		{
			MethodName: "RestartWorkflow",
			Handler:    _WorkflowService_RestartWorkflow_Handler,
		},
		{
			MethodName: "RetryWorkflow",
			Handler:    _WorkflowService_RetryWorkflow_Handler,
		},
		{
			MethodName: "ResetWorkflowCallbacks",
			Handler:    _WorkflowService_ResetWorkflowCallbacks_Handler,
		},
		{
			MethodName: "TerminateWorkflow",
			Handler:    _WorkflowService_TerminateWorkflow_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _WorkflowService_Search_Handler,
		},
		{
			MethodName: "SearchByTasks",
			Handler:    _WorkflowService_SearchByTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/workflow_service.proto",
}

func init() {
	proto.RegisterFile("grpc/workflow_service.proto", fileDescriptor_workflow_service_f78a771ea5b8eb25)
}

var fileDescriptor_workflow_service_f78a771ea5b8eb25 = []byte{
	// 1149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x5d, 0x6f, 0xdb, 0x36,
	0x17, 0x86, 0xed, 0x34, 0x89, 0x4f, 0xe2, 0x7c, 0xb0, 0x49, 0xea, 0x28, 0x68, 0x5f, 0xbf, 0x1a,
	0x0a, 0xa4, 0x03, 0x26, 0x6f, 0x69, 0x8b, 0x04, 0xbd, 0xea, 0x92, 0x6c, 0x5d, 0x80, 0xa1, 0x28,
	0x98, 0x00, 0x03, 0x76, 0xa3, 0xc9, 0x12, 0xe3, 0x10, 0xd6, 0x87, 0x47, 0x52, 0x4e, 0x3d, 0xec,
	0x6a, 0xd8, 0xdd, 0xfe, 0xc2, 0xb0, 0x1f, 0xb2, 0xdb, 0xfd, 0xb1, 0x41, 0x14, 0x25, 0x5b, 0x32,
	0xad, 0xda, 0x01, 0x76, 0x67, 0x9f, 0x6f, 0x9e, 0xf3, 0xf0, 0x3c, 0xb4, 0xe1, 0xa8, 0xcf, 0x86,
	0x6e, 0xf7, 0x3e, 0x62, 0x83, 0x5b, 0x3f, 0xba, 0xb7, 0x39, 0x61, 0x23, 0xea, 0x12, 0x6b, 0xc8,
	0x22, 0x11, 0xa1, 0xb6, 0x1b, 0x85, 0x5e, 0xec, 0x8a, 0x88, 0x59, 0x89, 0x99, 0x95, 0x99, 0x71,
	0x63, 0x57, 0xba, 0x71, 0xe2, 0x30, 0xf7, 0x2e, 0x35, 0x36, 0xf6, 0x82, 0xc8, 0x23, 0x7e, 0x1e,
	0x4a, 0x49, 0x8f, 0x8a, 0x52, 0x1e, 0x07, 0x81, 0xc3, 0xc6, 0x45, 0x25, 0x1f, 0xd0, 0xa1, 0x70,
	0xf8, 0x80, 0x91, 0x9f, 0x63, 0xc2, 0x85, 0x52, 0x76, 0x94, 0x52, 0x38, 0x4c, 0x64, 0xee, 0x5a,
	0x0b, 0x46, 0x58, 0x1c, 0x6a, 0x2d, 0xcc, 0x33, 0xd8, 0xbf, 0x4e, 0xfc, 0x7f, 0x50, 0x5a, 0x4c,
	0xf8, 0x30, 0x0a, 0x39, 0x41, 0xff, 0x83, 0x8d, 0xfc, 0xcc, 0xd4, 0x6b, 0xd7, 0x3a, 0xb5, 0xe3,
	0x26, 0x86, 0x4c, 0x74, 0xe5, 0x99, 0x7f, 0xd6, 0xe0, 0xf1, 0x3b, 0x92, 0x3b, 0x72, 0x9c, 0xc6,
	0x45, 0x08, 0x56, 0x42, 0x27, 0x20, 0xca, 0x43, 0x7e, 0x46, 0xcf, 0x61, 0xcb, 0x8d, 0x18, 0x23,
	0xbe, 0x23, 0x68, 0x14, 0x26, 0xf1, 0xea, 0x9d, 0xc6, 0x71, 0x13, 0xb7, 0xa6, 0xa4, 0x57, 0x5e,
	0x62, 0x46, 0x43, 0xd7, 0x8f, 0x3d, 0x62, 0xbb, 0x7e, 0xc4, 0x89, 0xd7, 0x6e, 0x74, 0x6a, 0xc7,
	0xeb, 0xb8, 0xa5, 0xa4, 0x17, 0x52, 0x88, 0x3e, 0x83, 0x4c, 0x60, 0x27, 0x4d, 0xe1, 0xed, 0x15,
	0x69, 0xb5, 0xa9, 0x84, 0x37, 0x89, 0xcc, 0xfc, 0xa7, 0x0e, 0x7b, 0xc5, 0xf2, 0xd4, 0xc1, 0x28,
	0x6c, 0xe7, 0xbd, 0xb6, 0x7b, 0xe3, 0xf4, 0x70, 0x8d, 0xe3, 0x8d, 0x93, 0xaf, 0xad, 0x79, 0xc3,
	0xb4, 0x74, 0x81, 0xac, 0x5c, 0x72, 0x3e, 0xbe, 0xf2, 0xbe, 0x09, 0x05, 0x1b, 0xe3, 0xd6, 0xfd,
	0xb4, 0xcc, 0xb8, 0x84, 0x66, 0x6e, 0x84, 0x4e, 0xa1, 0x99, 0x6b, 0x55, 0xc6, 0xc3, 0xa9, 0x8c,
	0x72, 0x1c, 0x79, 0x4c, 0x3c, 0xb1, 0x35, 0x7e, 0x01, 0x34, 0x9b, 0x0a, 0xed, 0x40, 0x63, 0x40,
	0xc6, 0xaa, 0xcb, 0xc9, 0x47, 0xf4, 0x1e, 0x1e, 0x8d, 0x1c, 0x3f, 0x26, 0xed, 0x7a, 0xa7, 0x76,
	0xbc, 0x71, 0x72, 0xf6, 0xd0, 0xe3, 0xe0, 0x34, 0xcc, 0x9b, 0xfa, 0x59, 0xcd, 0xfc, 0x09, 0xda,
	0x53, 0xc6, 0xd7, 0xc2, 0x11, 0x71, 0x3e, 0xe8, 0x4f, 0x21, 0x64, 0x76, 0x4e, 0x75, 0xcd, 0x9c,
	0x30, 0x1c, 0x6a, 0x32, 0xa8, 0x59, 0xbd, 0x86, 0xf5, 0x2c, 0x9e, 0x8c, 0x5f, 0xd9, 0xb2, 0xdc,
	0xd4, 0x74, 0x61, 0x1f, 0x93, 0x20, 0x1a, 0x91, 0x09, 0xaa, 0xcb, 0x25, 0x7b, 0xb3, 0x25, 0x7b,
	0x57, 0x1e, 0x7a, 0x01, 0x3b, 0xc9, 0x85, 0xa5, 0x23, 0x62, 0xe7, 0x89, 0xd3, 0xaa, 0xb7, 0x95,
	0x3c, 0x0b, 0x69, 0xb6, 0xe1, 0xa0, 0x9c, 0x24, 0xad, 0xda, 0xfc, 0xbd, 0x06, 0xc6, 0x3b, 0x22,
	0x70, 0x1c, 0x86, 0x34, 0xec, 0x2f, 0x74, 0x41, 0xda, 0xb0, 0x36, 0x22, 0x8c, 0xd3, 0x28, 0x94,
	0xe9, 0x1e, 0xe1, 0xec, 0x2b, 0x7a, 0x0a, 0x20, 0x2f, 0xb8, 0x2d, 0x68, 0x40, 0xe4, 0x7d, 0x68,
	0xe0, 0xa6, 0x94, 0xdc, 0xd0, 0x80, 0xa0, 0x43, 0x58, 0x27, 0xa1, 0x97, 0x2a, 0x57, 0xa4, 0x72,
	0x8d, 0x84, 0x5e, 0xa2, 0x32, 0xdf, 0xc2, 0x91, 0xb6, 0x0a, 0xd5, 0xdb, 0xff, 0xc3, 0xe6, 0xd4,
	0xf8, 0x52, 0x48, 0x36, 0xf1, 0xc6, 0x64, 0x7e, 0x3c, 0x59, 0x0e, 0x97, 0xc4, 0xa5, 0x5e, 0x45,
	0x1f, 0xe7, 0x2c, 0x87, 0x36, 0x1c, 0x94, 0x3d, 0x55, 0x73, 0x4e, 0x61, 0xef, 0x83, 0x13, 0xf3,
	0xe5, 0x43, 0x3e, 0x81, 0xfd, 0x92, 0xa3, 0x8a, 0x78, 0x96, 0x4c, 0x9b, 0xc7, 0xc1, 0x83, 0xaa,
	0x2c, 0x7b, 0xaa, 0x98, 0x7f, 0xd5, 0x60, 0xfb, 0x7a, 0x40, 0x87, 0x09, 0x46, 0x17, 0xc6, 0xbb,
	0x05, 0x8f, 0x13, 0x9c, 0xdb, 0x8c, 0xdc, 0x12, 0x46, 0x42, 0x97, 0xd8, 0x72, 0xce, 0x75, 0x69,
	0xb8, 0x2b, 0x64, 0x28, 0xa5, 0x79, 0x9f, 0x0c, 0xfd, 0x0d, 0xac, 0xa9, 0x65, 0x2c, 0xe7, 0xba,
	0x71, 0xd2, 0x99, 0x01, 0x77, 0xa9, 0x06, 0x9c, 0x39, 0x98, 0x08, 0x76, 0x26, 0xba, 0xe9, 0x46,
	0xb0, 0x38, 0x5c, 0x7e, 0x97, 0x47, 0xb2, 0x11, 0x45, 0x1e, 0x58, 0xf0, 0xd0, 0xaf, 0xe0, 0x20,
	0xe6, 0xc4, 0xf6, 0x1d, 0x41, 0xb8, 0xb0, 0x3d, 0x72, 0x4b, 0x43, 0x9a, 0xac, 0xf3, 0xec, 0xb6,
	0xef, 0xc5, 0x9c, 0x7c, 0x2f, 0x95, 0x97, 0x13, 0x9d, 0x79, 0x08, 0x4f, 0x66, 0x12, 0x4e, 0x00,
	0x82, 0x89, 0x60, 0xe3, 0x87, 0x00, 0xa4, 0xe4, 0xa8, 0x22, 0xbe, 0x85, 0xa7, 0x98, 0xf0, 0xc9,
	0x92, 0xb9, 0x70, 0x7c, 0xbf, 0xe7, 0xb8, 0x83, 0x85, 0x37, 0x99, 0xd9, 0x81, 0x67, 0xf3, 0x22,
	0xa8, 0x1c, 0xd7, 0xd0, 0xbe, 0x21, 0x2c, 0xa0, 0xa1, 0x23, 0x96, 0xc6, 0x21, 0x3a, 0x80, 0x55,
	0x46, 0x1c, 0xae, 0x2e, 0x7f, 0x13, 0xab, 0x6f, 0xe6, 0x11, 0x1c, 0x6a, 0x82, 0xaa, 0x8c, 0x1f,
	0xe1, 0x28, 0xdf, 0x9a, 0xe9, 0x9b, 0xe1, 0x5a, 0x3e, 0x36, 0x12, 0x44, 0xfb, 0x22, 0xd9, 0x1b,
	0x22, 0x12, 0x8e, 0x6f, 0xdf, 0x51, 0xc1, 0x65, 0xce, 0x06, 0x6e, 0x4a, 0xc9, 0x77, 0x54, 0xf0,
	0x14, 0x7b, 0x89, 0x21, 0x97, 0x54, 0xac, 0xc3, 0x5e, 0x29, 0x3a, 0xce, 0x1c, 0x4e, 0xfe, 0xde,
	0x82, 0xed, 0x5c, 0x99, 0x3e, 0x87, 0x50, 0x1f, 0x5a, 0x85, 0x77, 0x04, 0x7a, 0x3e, 0x8b, 0x65,
	0x0d, 0xbe, 0x8c, 0xee, 0x7c, 0x96, 0xd2, 0xbf, 0x4b, 0x02, 0xd8, 0x9c, 0xa6, 0x2f, 0xf4, 0xc5,
	0xa2, 0x34, 0x97, 0xe6, 0xb3, 0x96, 0x63, 0x45, 0xd4, 0x83, 0xdd, 0x19, 0x7a, 0x42, 0x27, 0x0b,
	0x05, 0x29, 0xb0, 0xa5, 0x31, 0x9f, 0xb8, 0x10, 0x87, 0xad, 0x22, 0x93, 0xa0, 0x8a, 0xae, 0x68,
	0x89, 0xcd, 0xf8, 0x72, 0x71, 0x07, 0x75, 0xb0, 0xdf, 0xd2, 0xe7, 0x5b, 0x99, 0x1e, 0xd0, 0xab,
	0xca, 0xb3, 0xcd, 0xe1, 0x34, 0xe3, 0xf5, 0x92, 0x5e, 0xaa, 0x08, 0x0e, 0x5b, 0x45, 0x9a, 0xa8,
	0x3a, 0xb9, 0x96, 0x8a, 0xaa, 0x4e, 0xae, 0x67, 0x20, 0x34, 0x84, 0x56, 0x81, 0x48, 0x50, 0x05,
	0x26, 0x74, 0x54, 0x55, 0x85, 0x59, 0x2d, 0x43, 0xa5, 0x03, 0x9e, 0xe6, 0x99, 0xea, 0x01, 0x6b,
	0xb8, 0xac, 0x7a, 0xc0, 0x3a, 0x0a, 0x43, 0x01, 0xec, 0x65, 0x0c, 0xf1, 0x2d, 0x8b, 0x82, 0x3c,
	0xf5, 0x8b, 0x8a, 0x1b, 0x57, 0x64, 0x1b, 0xe3, 0xf3, 0x45, 0x4c, 0x55, 0xba, 0x3e, 0xb4, 0x0a,
	0xe4, 0xa3, 0x59, 0x00, 0x25, 0x72, 0xfa, 0x64, 0x33, 0xf5, 0x64, 0x36, 0x82, 0xed, 0x12, 0x75,
	0xa0, 0xea, 0xe6, 0xe8, 0xd6, 0xce, 0x57, 0x4b, 0x78, 0x4c, 0x60, 0x53, 0xa0, 0x97, 0x2a, 0xd8,
	0xe8, 0x08, 0xac, 0xfa, 0xa4, 0x1a, 0xde, 0x42, 0x7f, 0xd4, 0x24, 0x2d, 0x6b, 0x68, 0x07, 0x9d,
	0x56, 0xd6, 0x3f, 0x9f, 0xea, 0x8c, 0xb3, 0xe5, 0x1d, 0x55, 0x35, 0xbf, 0xc2, 0xee, 0x0c, 0x19,
	0x55, 0x6d, 0xc2, 0x79, 0x74, 0x68, 0xbc, 0x5c, 0xca, 0x47, 0x65, 0xb7, 0x61, 0x35, 0xa5, 0x37,
	0xf4, 0xac, 0xec, 0xae, 0x7e, 0x63, 0x2f, 0xb0, 0x8a, 0xaa, 0xf8, 0xf2, 0x16, 0x5a, 0xe9, 0xf7,
	0xf3, 0xb1, 0xfc, 0x61, 0xf2, 0x1f, 0xe5, 0x39, 0x17, 0x60, 0xb8, 0x51, 0x60, 0x85, 0x44, 0xdc,
	0xfa, 0xf4, 0x63, 0x29, 0xc6, 0xf9, 0x6e, 0x89, 0x57, 0x3f, 0xf4, 0x7e, 0xbc, 0xe8, 0x53, 0x71,
	0x17, 0xf7, 0x2c, 0x37, 0x0a, 0xba, 0xca, 0xab, 0x9b, 0x7b, 0x75, 0x5d, 0x9f, 0x92, 0x50, 0x74,
	0xfb, 0x91, 0xfc, 0xbb, 0x61, 0x22, 0x2f, 0xfc, 0x69, 0xc1, 0x7b, 0xab, 0xf2, 0x06, 0xbe, 0xfc,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x04, 0xeb, 0x27, 0x3c, 0xcd, 0x10, 0x00, 0x00,
}
