# docker-compose -f docker/docker-compose-oracle.yaml up
## Run the above command from conductor root directory

version: '2.3'

services:
  conductor-server:
    environment:
      - CONFIG_PROP=config-oracle.properties
    image: conductor:server
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    networks:
      - internal
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl","-I" ,"-XGET", "http://localhost:8080/health"]
      interval: 60s
      timeout: 30s
      retries: 12
    links:
      - elasticsearch:elasticsearch
      - oracle:oracle
    depends_on:
      elasticsearch:
        condition: service_healthy
      oracle:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  oracle:
    image: conductorboot/oracle:19.3.0-ee-slim
    volumes:
      - oracle_startup_scripts:/opt/oracle/scripts/setup
    environment:
      - ORACLE_SID=CONDUCTR
      - ORACLE_PDB=CONDUCTOR
      - ORACLE_PWD=Conductor@1234
      - ORACLE_EDITION=enterprise
    healthcheck:
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 180s
    ports:
      - 1521:1521
      - 5500:5500
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

  conductor-ui:
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    image: conductor:ui
    build:
      context: ../
      dockerfile: docker/ui/Dockerfile
    networks:
      - internal
    ports:
      - 5000:5000
    links:
      - conductor-server:conductor-server

  elasticsearch:
    image: elasticsearch:6.8.15
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - transport.host=0.0.0.0
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - internal
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/9300'
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

volumes:
  oracle_startup_scripts:
    driver: local
    driver_opts:
      type: none
      device: $PWD/docker/persistence/oracle
      o: bind

networks:
  internal: