# Docker compose for netflix conductor + elasticsearch + dynomite
version: '2'
services:
  conductor-server:
    environment:
      - db=dynomite
      - workflow.dynomite.cluster.hosts=dyno1:8102:us-east-1c
      - workflow.dynomite.cluster.name=dyno1
      - workflow.namespace.prefix=conductor
      - workflow.namespace.queue.prefix=conductor_queues
      - queues.dynomite.threads=10
      - queues.dynomite.nonQuorum.port=22122
      - workflow.elasticsearch.url=es:9300
      - workflow.elasticsearch.index.name=conductor
      - loadSample=true      
    image: conductor:server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch
      - dynomite
    networks:
      conductornet:
        aliases:
          - conductor-server

  conductor-ui:
    environment:
      - WF_SERVER=http://conductor-server:8080/api/
    image: conductor:ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - conductor-server
    networks:
      conductornet:
        aliases:
          - conductor-ui

  dynomite:
    image: v1r3n/dynomite
    ports:
      - 8102:8102
      - 22122:22122
      - 22222:22222
    networks:
      conductornet:
        aliases:
          - dyno1

  elasticsearch:
    image: elasticsearch:2.4
    ports:
      - 9300:9300
      - 9200:9200
    networks:
      conductornet:
        aliases:
          - es

networks:
  conductornet:
    driver: bridge
