version: '2.3'

services:
  conductor-server:
    environment:
      - CONFIG_PROP=config.properties
    links:
      - dynomite:dyno1
    depends_on:
      dynomite:
        condition: service_healthy

  dynomite:
    image: v1r3n/dynomite
    networks:
      - internal
    ports:
      - 8102:8102
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/8102'
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

networks:
  internal:
