version: '3.1'

services:

  mysqldb:
    image: mysql
    restart: always
    ports:
      - "33307:3306"
    volumes:
      - ".docker/mysqldb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root

  postgresdb:
    image: postgres
    restart: always
    ports:
      - "54320:5432"
    volumes:
      - ".docker/postgresdb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: postgres

  sqlserver:
    image: conductor:sqlserver
    build: 
      context: ../sqlserver-persistence/docker
      dockerfile: sqlserver/Dockerfile
    restart: always
    ports:
    - "1433:1433"
    healthcheck:
      test: timeout 5 bash -c '/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Password1 -l 3 -t 3 -d Conductor -Q "SELECT 1"'
      interval: 5s
      timeout: 5s
      retries: 50
    environment:
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: "Password1"
      MSSQL_PID: 'Developer'
      MSSQL_AGENT_ENABLED: 'false'
