apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "netflix-conductor.name" . }}-config
data:
  {{- (tpl (.Files.Glob "files/conductor-config.properties").AsConfig .) | nindent 2 }}
  {{- (tpl (.Files.Glob "files/log4j.properties").AsConfig .) | nindent 2 }}