{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    genre: "conductor"
    draft: {{ default "draft-app" .Values.draft }}
    app: {{ include "netflix-conductor.name" . }}-server
    application: {{ include "netflix-conductor.name" . }}-server
  name: {{ .Values.serviceAccount.name }}
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
  {{- end }}