apiVersion: v1
kind: Service
metadata:
  name: {{ include "netflix-conductor.name" . }}-server
  labels:
    app: {{ include "netflix-conductor.name" . }}
    chart: {{ include "netflix-conductor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: server
      protocol: TCP
      port: 8080
      targetPort: server
  selector:
    app: {{ include "netflix-conductor.name" . }}
    release: {{ .Release.Name }}
    component: server