ALTER SESSION SET CONTAINER=ORCLPDB1;
CREATE USER conductor IDENTIFIED BY conductor;
GRANT CONNECT, RESOURCE, CREATE SESSION, DBA, DV_REALM_RESOURCE TO conductor;
ALTER USER conductor QUOTA UNLIMITED ON USERS;
exit;