[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.15.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"
