name: Close stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale, because it has been open for 45 days with no activity. Remove the stale label or comment, or this will be closed in 7 days.'
          close-issue-message: 'This issue was closed, because it has been stalled for 7 days with no activity.'
          stale-pr-message: 'This PR is stale, because it has been open for 45 days with no activity. Remove the stale label or comment, or this will be closed in 7 days.'
          close-pr-message: 'This PR was closed, because it has been stalled for 7 days with no activity.'
          days-before-issue-stale: 45
          days-before-issue-close: 7
          days-before-pr-stale: 45
          days-before-pr-close: 7
          exempt-issue-labels: 'type: bug,enhancement,work_in_progress,help_wanted'
